name: Deploy to InfinityFree via FTP
on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_39687447
          password: 9TKPHkHPjqXQ
          server-dir: /htdocs/
          local-dir: .
          protocol: ftp
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            form_db/uploads/**
            form_db/config.php
            *.md
            *.env
