name: Test FTP to InfinityFree
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create test file
        run: echo "ok $(date -u)" > ping.txt
      - name: FTP upload (verbose)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_39687447
          password: 9TKPHkHPjqXQ
          server-dir: /htdocs/_gh_test/
          local-dir: .
          protocol: ftp
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
